<ReactNavbar
      burgerColorHover="a62d24"
      navColor1="rgba(0,0,0, 0.4)"
      logo = {logo}
      logoWidth = "20vmax"
      logoHoverSize = "10px"
      logoHoverColor ="#eb4034"
      link1Text = "Home"
      link2Text = "Product"
      link3Text = "Contact"
      link4Text = "About"
      link1Url = "/"
      link2Url = "/product"
      link3Url = "/contact"
      link4Url = "/about"
      link1Size = "2vmax"

      linkColor = "rgba(35,35,35, 0.8)"
      nav1JustifyContent = "flex-end"
      nav2JustifyContent = "flex-end"
      nav3JustifyContent = "flex-start"
      nav4JustifyContent = "flex-start"
      link1ColorHover = "#eb4034"
      link2ColorHover = "#eb4034"
      link3ColorHover = "#eb4034"
      link4ColorHover = "#eb4034"
      link2Margin = "1vmax"
      link4Marign = "1vmax"
      profileIconColor = "rgba(35, 35, 35, 0.8)"
      searchIconColor = "rgba(35, 35, 35, 0.8)"
      cartIconColor = "rgba(35, 35, 35, 0.8)"
      profileIconColorHOver = "#eb4034"
      searchIconColorHOver = "#eb4034"
      cartIconColorHOver = "#eb4034"

      searchIcon = "true"
      SearchIconElement ="required"
      searchIconSize = "2vmax"
      searchIconUrl= "/search"
      searchIconColor= "white"
      />